/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ctp4j;

import java.io.IOException;

public class ThostFtdcCtpApi implements ThostFtdcCtpApiConstants {
  public static void install() throws IOException {
    StaticDllLoader.install();
  }

  public static String getVersion() {
    return "ctp4j-1.0.4";
  }
}
