/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ctp4j;

public class ThostFtdcCtpApi implements ThostFtdcCtpApiConstants {
  static final StaticDllLoader dllLoader = new StaticDllLoader();

  // Version.
  public static final String Version = "ctp4j-1.0.4";
}
